"""Public model registry for schema generation and downstream validation."""

from __future__ import annotations

from peru_conflicts.models.common import (
    SCHEMA_VERSION,
    ModelInvocation,
    SourceBBox,
    SourceSpan,
    TransitionEvidence,
    VersionedModel,
)
from peru_conflicts.models.domain import (
    Actor,
    AdjudicationRecord,
    Agreement,
    Alert,
    CaseActor,
    CaseDemand,
    CaseLocation,
    CaseMonth,
    CaseName,
    CaseProtestLink,
    CaseRelationship,
    CasualtyComponent,
    ConflictCase,
    DefensoriaAction,
    Demand,
    DialogueEvent,
    DiscrepancyRecord,
    DiscrepancyType,
    ExtractionMethod,
    IndicatorBasis,
    Location,
    ManualReviewItem,
    MediationProcess,
    ProtestEvent,
    ProvenanceRecord,
    ReportIdentityEvidenceType,
    ReportMonthAggregate,
    ReportRecord,
    ViolenceEvent,
)

MODEL_REGISTRY: dict[str, type[VersionedModel]] = {
    "actor": Actor,
    "adjudication": AdjudicationRecord,
    "agreement": Agreement,
    "alert": Alert,
    "case": ConflictCase,
    "case_actor": CaseActor,
    "case_demand": CaseDemand,
    "case_location": CaseLocation,
    "case_month": CaseMonth,
    "case_name": CaseName,
    "case_protest_link": CaseProtestLink,
    "case_relationship": CaseRelationship,
    "demand": Demand,
    "dialogue_event": DialogueEvent,
    "discrepancy": DiscrepancyRecord,
    "dp_action": DefensoriaAction,
    "location": Location,
    "manual_review": ManualReviewItem,
    "mediation_process": MediationProcess,
    "protest_event": ProtestEvent,
    "provenance": ProvenanceRecord,
    "report": ReportRecord,
    "report_month": ReportMonthAggregate,
    "violence_event": ViolenceEvent,
}

__all__ = [
    "MODEL_REGISTRY",
    "SCHEMA_VERSION",
    "Actor",
    "AdjudicationRecord",
    "Agreement",
    "Alert",
    "CaseActor",
    "CaseDemand",
    "CaseLocation",
    "CaseMonth",
    "CaseName",
    "CaseProtestLink",
    "CaseRelationship",
    "CasualtyComponent",
    "ConflictCase",
    "DefensoriaAction",
    "Demand",
    "DialogueEvent",
    "DiscrepancyRecord",
    "DiscrepancyType",
    "ExtractionMethod",
    "IndicatorBasis",
    "Location",
    "ManualReviewItem",
    "MediationProcess",
    "ModelInvocation",
    "ProtestEvent",
    "ProvenanceRecord",
    "ReportIdentityEvidenceType",
    "ReportMonthAggregate",
    "ReportRecord",
    "SourceBBox",
    "SourceSpan",
    "TransitionEvidence",
    "ViolenceEvent",
]
